/* Solves the model equations of Qu et al. (2018) Siam J Appl Math, pp. 826--852
  that accounts for sexes and age class of mosquitoes, adapted to
  include two diffusively coupled habitats (A and B).  */

#include <iostream>
#include <fstream>
#include <cmath>
#include <cstdlib>

#include "parameters.h"

using namespace std;


ofstream ofsA ("infectedA.txt");    // proportion of FEMALES in Habitat A that carry Wolbachia
ofstream ofsB ("infectedB.txt");    // proportion of FEMALES in Habitat B that carry Wolbachia

int main() {


  double t = 0.0;
  double dt = 0.01;
  int counter = 0;
  double m;               //migration paramter
  cout << "Enter migration parameter m: ";
  cin >> m;
  cout << endl;

  double Aua, Auaold, Aub, Aubold, Awa, Awaold, Awb, Awbold;          //aquatic stage populations
  double Fua, Fuaold, Fub, Fubold, Fwa, Fwaold, Fwb, Fwbold;          //non-pregnant female populations
  double Fpua, Fpuaold, Fpub, Fpubold, Fpwa, Fpwaold, Fpwb, Fpwbold;  //pregnant female populations
  double Mua, Muaold, Mub, Mubold, Mwa, Mwaold, Mwb, Mwbold;          //male populations
  double Fpsa, Fpsaold, Fpsb, Fpsbold;                                //sterile female populations

  double infectedA, uninfectedA, infectedB, uninfectedB;              //for computing overall percent of infected ADULTS in each habitat

  /*  initial conditions */

  Auaold = 200000.0, Awaold = 300000.0, Fuaold = 300000.0, Fwaold = 500000.0, Fpuaold = 100000.0;
  Fpwaold = 100000.0, Muaold = 400000.0, Mwaold = 0.0, Fpsaold = 0.0;

  Aubold = 200000.0, Awbold = 0.0, Fubold = 800000.0, Fwbold = 0.0, Fpubold = 100000.0;
  Fpwbold = 0.0, Mubold = 400000.0, Mwbold = 0.0, Fpsbold = 0.0;

  /*  forward Euler ODE solver */

  while (t < 2500.0) {

    t = t + dt;
    counter++;
    Aua = Auaold + dt*((phiu*Fpuaold + vu*phiw*Fpwaold)*(1.0 - (Auaold + Awaold)/Ka) - (mmua + psi)*Auaold);
    Awa = Awaold + dt*(vw*phiw*Fpwaold*(1.0 - (Auaold + Awaold)/Ka) - (mmua + psi)*Awaold);
    Fua = Fuaold + dt*(bf*psi*Auaold - (sigma + mufu)*Fuaold + m*(Fubold - Fuaold));
    Fwa = Fwaold + dt*(bf*psi*Awaold - (sigma + mufw)*Fwaold + m*(Fwbold - Fwaold));
    Fpua = Fpuaold + dt*(sigma*Fuaold*Muaold/(Muaold + Mwaold) - mufu*Fpuaold + m*(Fpubold - Fpuaold));
    Fpwa = Fpwaold + dt*(sigma*Fwaold - mufw*Fpwaold + m*(Fpwbold - Fpwaold));
    Mua = Muaold + dt*(bm*psi*Auaold - mumu*Muaold + m*(Mubold - Muaold));
    Mwa = Mwaold + dt*(bm*psi*Awaold - mumw*Mwaold + m*(Mwbold - Mwaold));
    Fpsa = Fpsaold + dt*(sigma*Fuaold*Mwaold/(Muaold + Mwaold) - mufu*Fpsaold + m*(Fpsbold - Fpsaold));

    Aub = Aubold + dt*((phiu*Fpubold + vu*phiw*Fpwbold)*(1.0 - (Aubold + Awbold)/Ka) - (mmua + psi)*Aubold);
    Awb = Awbold + dt*(vw*phiw*Fpwbold*(1.0 - (Aubold + Awbold)/Ka) - (mmua + psi)*Awbold);
    Fub = Fubold + dt*(bf*psi*Aubold - (sigma + mufu)*Fubold + m*(Fuaold - Fubold));
    Fwb = Fwbold + dt*(bf*psi*Awbold - (sigma + mufw)*Fwbold + m*(Fwaold - Fwbold));
    Fpub = Fpubold + dt*(sigma*Fubold*Mubold/(Mubold + Mwbold) - mufu*Fpubold + m*(Fpuaold - Fpubold));
    Fpwb = Fpwbold + dt*(sigma*Fwbold - mufw*Fpwbold + m*(Fpwaold - Fpwbold));
    Mub = Mubold + dt*(bm*psi*Aubold - mumu*Mubold + m*(Muaold - Mubold));
    Mwb = Mwbold + dt*(bm*psi*Awbold - mumw*Mwbold + m*(Mwaold - Mwbold));
    Fpsb = Fpsbold + dt*(sigma*Fubold*Mwbold/(Mubold + Mwbold) - mufu*Fpsbold + m*(Fpsaold - Fpsbold));

    infectedA   = Fwa + Fpwa + Fpsa;    //these are the three adult female populations that are infected with Wolbachia
    uninfectedA = Fua + Fpua;           //these are the two adult female populations that are NOT infected with Wolbach
    infectedB   = Fwb + Fpwb + Fpsb;    //these are the three adult female populations that are infected with Wolbachia
    uninfectedB = Fub + Fpub;           //these are the two adult female populations that are NOT infected with Wolbach

    if ((counter%10) == 0) {
      ofsA << t << "\t" << (infectedA/(infectedA + uninfectedA)) << endl;
      ofsB << t << "\t" << (infectedB/(infectedB + uninfectedB)) << endl;
    }

    Auaold = Aua,  Awaold = Awa,  Fuaold = Fua,  Fwaold = Fwa,  Fpuaold = Fpua,  Fpwaold = Fpwa,  Muaold = Mua,  Mwaold = Mwa,  Fpsaold = Fpsa;
    Aubold = Aub,  Awbold = Awb,  Fubold = Fub,  Fwbold = Fwb,  Fpubold = Fpub,  Fpwbold = Fpwb,  Mubold = Mub,  Mwbold = Mwb,  Fpsbold = Fpsb;

  }


  /* Comment out the next line if you prefer to use software other than gnuplot to
     generate figures from the .txt files generated by this program.  If you do have
     gnuplot installed, you may need to change the path for calling gnuplot.  */


  system ("/Applications/Gnuplot.app/Contents/Resources/bin/gnuplot quplot");

  return 0;

}
